CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS messages
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message varchar(1024) not null,
    created timestamp without time zone,
    user_id bigint        not null
        constraint messages_user_id
            references users (id)
            on update cascade on delete cascade
);